name: Fork-Specific Issue
description: Report an issue that appears to be specific to this fork, not present in upstream NVIDIA/earth2studio
title: "[FORK] "
labels: ["fork-specific", "triage"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for reporting an issue! This template is for problems that appear to be specific to this fork.
        
        **Before submitting:**
        - Check if the issue exists in [upstream NVIDIA/earth2studio](https://github.com/NVIDIA/earth2studio/issues)
        - Search existing issues to avoid duplicates
        - Review [KNOWN_ISSUES.md](../../../KNOWN_ISSUES.md) for documented problems

  - type: checkboxes
    id: checks
    attributes:
      label: Pre-submission checks
      options:
        - label: I have searched existing issues and this is not a duplicate
          required: true
        - label: I have checked this issue does NOT exist in upstream NVIDIA/earth2studio
          required: true
        - label: I have reviewed KNOWN_ISSUES.md
          required: true

  - type: input
    id: fork-version
    attributes:
      label: Fork Version
      description: What version of the fork are you using?
      placeholder: "e.g., 0.12.0-fork.1, or commit hash"
    validations:
      required: true

  - type: dropdown
    id: issue-type
    attributes:
      label: Issue Type
      description: What type of issue is this?
      options:
        - Bug in fork-specific code
        - Performance issue
        - Documentation issue
        - Installation/setup issue
        - Memory optimization issue
        - GPU compatibility issue
        - Other
    validations:
      required: true

  - type: textarea
    id: description
    attributes:
      label: Issue Description
      description: Provide a clear description of the issue
      placeholder: What is happening? What did you expect to happen?
    validations:
      required: true

  - type: textarea
    id: reproduction
    attributes:
      label: Steps to Reproduce
      description: Provide detailed steps to reproduce the issue
      placeholder: |
        1. Install fork with `pip install ...`
        2. Run script with `python ...`
        3. Observe error ...
    validations:
      required: true

  - type: textarea
    id: code
    attributes:
      label: Minimal Code Example
      description: Provide a minimal code example that demonstrates the issue
      placeholder: |
        ```python
        from earth2studio.models.px import FCN3
        # Your code here
        ```
      render: python

  - type: textarea
    id: error
    attributes:
      label: Error Message / Output
      description: Include the complete error message or unexpected output
      placeholder: |
        Paste the full traceback or output here
      render: shell

  - type: textarea
    id: system
    attributes:
      label: System Information
      description: Provide details about your system
      placeholder: |
        - OS: Ubuntu 24.04
        - Python version: 3.12
        - PyTorch version: 2.5.1
        - CUDA version: 12.8
        - GPU: RTX 4090 24GB
        - Installation method: pip/uv/source
    validations:
      required: true

  - type: textarea
    id: comparison
    attributes:
      label: Comparison with Upstream
      description: Have you tested this with upstream NVIDIA/earth2studio?
      placeholder: |
        - Tested with upstream? Yes/No
        - If yes, does the issue occur there? Yes/No
        - Differences observed: ...

  - type: textarea
    id: workarounds
    attributes:
      label: Attempted Workarounds
      description: What have you tried to fix or work around this issue?
      placeholder: |
        - Tried solution 1: ...
        - Tried solution 2: ...

  - type: textarea
    id: additional
    attributes:
      label: Additional Context
      description: Add any other context, screenshots, or information
      placeholder: Any other details that might be helpful

  - type: dropdown
    id: contribution
    attributes:
      label: Willing to Contribute Fix
      description: Would you be willing to contribute a fix for this issue?
      options:
        - "Yes"
        - "Maybe"
        - "No"
